issuer:
  createIssuer: true
  name: "my-custom-issuer"
  namespace: "default"
  kind: "Issuer" # Can also be ClusterIssuer
  email: "email@example.com"
  privateKeySecretRef:
    name: "letsencrypt-http01-account-key"
  solvers:
    http01:
      ingress:
        class: "traefik"
certificate:
  createCertificate: true
  name: "my-certificate"
  namespace: "default"
  commonName: "example.com"
  dnsName: "example.com"
  duration: "2160h" # 90 days
  renewBefore: "360h" # 15 days

