issuer:
  name: "my-custom-issuer"
  namespace: "default"
  kind: "Issuer" # Can also be ClusterIssuer
certificate:
  name: "my-certificate"
  namespace: "default"
  secretName: "my-tls-secret"
  commonName: "example.com"
  dnsNames: []
  duration: "2160h" # 90 days
  renewBefore: "360h" # 15 days
