apiVersion: cert-manager.io/v1
kind: {{ .Values.issuer.kind }}
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.issuer.namespace }}
spec:
  ca:
    secretName: ca-key-pair # Adjust as per your CA
