{{ if .Values.issuer.createIssuer }}
apiVersion: cert-manager.io/v1
kind: {{ .Values.issuer.kind }}
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.issuer.namespace }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.issuer.privateKeySecretRef.name }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: {{ .Values.issuer.solvers.http01.ingress.class }}
{{ end }}
